### ISSUE TITLE
Having issues in running the paraphraser.

### ISSUE THREAD

**Issue by JafferWilson** [lachenmayer/paraphraser#1]
This is the issue I have face while runni g your code. Can you help?
> Traceback (most recent call last):
>   File "testrephrase.py", line 36, in <module>
>     print (paraphrase("The quick brown fox jumps over the lazy dog."))
>   File "testrephrase.py", line 33, in paraphrase
>     return [x for x in synonymIfExists(sentence)]
>   File "testrephrase.py", line 33, in <listcomp>
>     return [x for x in synonymIfExists(sentence)]
>   File "testrephrase.py", line 25, in synonymIfExists
>     syns = synonyms(word, t)
>   File "testrephrase.py", line 20, in synonyms
>     return set([lemma.name for lemma in sum([ss.lemmas for ss in wn.synsets(word, pos(tag))],[])])
> TypeError: can only concatenate list (not "method") to list
>

**Comment by mprzydatek** [comment]
+1 
any idea how to get rid of this error?

**Comment by JafferWilson** [comment]
How would I know about it @mprzydatek ? I have asked the query. If I knew the reason for this happening I would have removed it already.

**Comment by lachenmayer** [comment]
Hey folks, this is just an experiment I wrote in my spare time while in college, I don't think it will actually work at all anymore.

At the time I wrote this in Python 2 not 3, so it's possible that this is the cause of that error.

Additionally, this repo doesn't specify any dependencies, and at the very least you'll need `nltk`, and probably a few others.

It would probably be easier to write your own code based on the stuff in `paraphraser.py` than to try to get this to actually run.

Let me know if you do attempt it, would be great to see your results!
